name: build

on:
  push:
  pull_request:
    branches: [ main, develop, release ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use

jobs:
  build:

    name: build-validator
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore codigo/backend/PharmaGo.sln
      
    - name: Build
      run: dotnet build --configuration Release --no-restore codigo/backend/PharmaGo.sln