name: test-validation

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0.400' # The .NET SDK version to use

jobs:
  build:

    name: test-validation-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    os: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore codigo/backend/PharmaGo.sln
      
    - name: test
      run: dotnet test --configuration Release --no-restore codigo/backend/PharmaGo.sln